#
#  Enrole Inc.
#  Copyright (C) - 2020
#
#  File Name: .gitlab-ci.yml
#  Description: Defines CI/CD Pipelines to deploy CF Macros
#  Creation Date: 05/21/2020
#
#  This file is owned by Enrole Inc.
#
#  Distribution and duplication of this source code outside of the organization
#  is prohibited.
#

default:
  image: git.internal.enroleapp.com:5050/enrole/crypt/docker-images/enrole-api-cicd:1.0.4

stages:
  - test
  - deploy

deploy-production:
  stage: deploy
  only:
    - master
  before_script:
    - npm config set @enrole:registry https://git.internal.enroleapp.com/api/v4/packages/npm/
    - npm config set '//git.internal.enroleapp.com/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - STACKNAME=cf-macros
  script:
    - sam deploy
      --profile EnroleApp-Production
      --s3-bucket enroleapp-production-aws-sam-bucket
      --s3-prefix $STACKNAME
      --stack-name $STACKNAME
      --region us-east-1
      --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
      --no-confirm-changeset
      --no-fail-on-empty-changeset

deploy-development:
  stage: deploy
  only:
    - master
  before_script:
    - npm config set @enrole:registry https://git.internal.enroleapp.com/api/v4/packages/npm/
    - npm config set '//git.internal.enroleapp.com/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - STACKNAME=cf-macros
  script:
    - sam deploy
      --profile EnroleApp-Development
      --s3-bucket enroleapp-development-aws-sam-bucket
      --s3-prefix $STACKNAME
      --stack-name $STACKNAME
      --region us-east-1
      --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
      --no-confirm-changeset
      --no-fail-on-empty-changeset
